### ISSUE TITLE
Instructions to import into project

### ISSUE THREAD

**Issue by khalid-hussain** [vanniktech/VNTNumberPickerPreference#2]
Hi there,

I'm interested in using this library along with your other library, [VNTFontListPreference](https://github.com/vanniktech/VNTFontListPreference).

I feel it is out-of-date in terms of gradle instructions. Can you please sort this out or provide more clear instructions?

Currently, this is what I have:
**settings.gradle**
```
include ':app', ':vntnumberpickerpreference'
project(':vntnumberpickerpreference').projectDir = new File(settingsDir, '/path/VNTNumberPickerPreference/library')
```

**build.gradle**
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.1"

    defaultConfig {
        applicationId "com.example.khalid.hisnulmuslim"
        minSdkVersion 14
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
}


dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:cardview-v7:21.0.3'
    compile 'com.android.support:recyclerview-v7:21.0.3'
    compile 'com.android.support:support-v4:21.0.3'
    compile 'com.joanzapata.android:android-iconify:1.0.8'
    compile 'com.github.bluejamesbond:textjustify-android:1.5.1'
    compile project(':vntnumberpickerpreference')
}
```
But it is still giving me error(s). The following is what I get:
```
Error:Configuration with name 'default' not found.
```

I'm a beginner at Android development and am not quite sure where the problem lies. Thanks for your time.

**Comment by vanniktech** [comment]
Hi,

yep I have to deploy it somewhere, so you could include it in one line 
instead of downloading it from GitHub.

Most probably you haven't downloaded the repository on your local 
machine. If so do now and place it somewhere.
'/path/VNTFontListPreference/library' references to a valid path on your 
machine, where the library folder is located. So you probably have to 
change it and then it should work.

Cheers
Nik

**Comment by khalid-hussain** [comment]
Thanks for the quick reply. Alhamdulillah, I've found a beginner-friendly tutorial over [here](http://stackoverflow.com/questions/16588064/how-do-i-add-a-library-project-to-the-android-studio).

**Comment by vanniktech** [comment]
@khalid-hussain 
I've had the time to put the stuff into Sonatype, see the updated README for further instructions on how to include the library in your project. Enjoy!

**Comment by khalid-hussain** [comment]
Great Work!
