### ISSUE TITLE
Prevent infinite scrolling

### ISSUE THREAD

**Issue by khalid-hussain** [vanniktech/VNTNumberPickerPreference#3]
Hi there,

Is there a way to prevent infinite scrolling of the numbers? For example if my limits are 10-20, I don't want to allow the user to scroll past 20 and into 10 again. I'd rather the list have an ending and a beginning like a regular listView. Is this possible?

Thanks for your time.

**Comment by vanniktech** [comment]
First thing in the README.md ...

**Comment by khalid-hussain** [comment]
I don't find such an explanation in the README. I was hoping for some option to help tweak an option similiar to [setWrapSelectorWheel](http://developer.android.com/reference/android/widget/NumberPicker.html#setWrapSelectorWheel(boolean)) from the XML.

Thanks.

**Comment by vanniktech** [comment]
Oh okay I totally mixed things up. There is no support for that, although it would be easy to provide another configuration for that particular feature.

Again if you want, you can submit a PR.
