### ISSUE TITLE
Default value not working

### ISSUE THREAD

**Issue by evasquez26** [vanniktech/VNTNumberPickerPreference#40]
Hi thanks for this great library!
I think I've encountered an issue when you don't pick any value, it should select the default value and persist in the preferences, but it's not being saved. I believe there's only one line missing here

```java
@Override
    protected void onSetInitialValue(final boolean restoreValue, final Object defaultValue) {
        final int intDefaultValue = defaultValue instanceof Integer ? (int) defaultValue : minValue;
        selectedValue = restoreValue ? this.getPersistedInt(intDefaultValue) : intDefaultValue;
        this.updateSummary();
        this.persistInt(selectedValue); // add this here
    }
```

**Comment by vanniktech** [comment]
I don't think this is an issue. As you can see in the example the `Body size` is already 180 because the default value was set to it.

**Comment by evasquez26** [comment]
Yes but when you leave the settings without touching the number picker the key and its default value are not stored, is this expected?

**Comment by vanniktech** [comment]
Why should they be stored, you'll get the default value without the need of storing it. At least that's how I see it.

**Comment by evasquez26** [comment]
I see, I'm kind of new to Android, I was expecting them to be saved when you leave the settings but the default value from shared preferences works as well. Thank you!
